spring:
  application:
    name: Spring Boot 3 Otel Demo
management:
  otlp:
    metrics:
      export:
        enabled: false
        step: 1m
        url: https://otlp.eu01.nr-data.net
  tracing:
    sampling:
      probability: 1.0f

logging:
  level:
    root: debug
